---
title: Diagnostics for randomized data (GLOPNET)
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
#rmdformats::material
  html_document:
    fig_caption: yes
    theme: spacelab #readable #sandstone #spacelab #flatly
    highlight: pygments #tango #kate
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    toc_float:
      collapsed: TRUE
      smooth_scroll: TRUE
      toc: true
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE,
                      cache=FALSE,
                      message=FALSE)
```

```{r}

library(tidyverse)
library(rstan)
library(scales)
library(memisc)
library(bayesplot)

settings <- yaml::yaml.load_file("settings.yml")
```

```{r}

load("rda/GL_LMAms_more_rand.rda")
#PA_LMAms_L0_more_rand.rda

```

# Diagnostics

```{r}

#color_scheme_set("darkgray")
color_scheme_set("mix-brightblue-gray")

check_trace <- function(x) {
  fit <- rand_res$model[[x]]
  np_cp <- nuts_params(fit)
  mcmc_trace(fit, pars = c("Z[2,3]", "lp__"), np = np_cp) +
    ggtitle(str_c("Rand", x, sep = " "))
}


p <- 1:9  %>%
  map(check_trace)

p %>%
  walk(print)

```

```{r}
# good
summary_GL_LDL <- rand_res$summary[[8]]

summary_GL_LDL %>% 
  round(3) %>%
  DT::datatable(.)

temp <- rand_dat$data[[1]] 

GL0 <- dat %>%
  as_tibble %>%
  dplyr::select(sp, DE, GF)

GL <- tibble(LMA = temp$LMA,
                 Aarea = temp$A,
                 LL = temp$LL,
                 Rarea = temp$R)

GL <- bind_cols(GL0, GL)


#P_vec <- paste("p[", 1:nrow(GL), "]", sep = "")
LMAp_vec <- paste("log_LMAp[", 1:nrow(GL), "]", sep = "")
LMAs_vec <- paste("log_LMAs[", 1:nrow(GL), "]", sep = "")
mu2_vec <- paste("Mu[", 1:nrow(GL), ",2]", sep = "")
#Mu_vec <- paste("mu[", 1:nrow(GL), ",2]", sep = "")
temp_LMAp <- summary_GL_LDL[LMAp_vec, "mean"] 
temp_LMAs <- summary_GL_LDL[LMAs_vec, "mean"] 
temp_LL <- exp(summary_GL_LDL[mu2_vec, "mean"])

GL <- GL %>%
  mutate(LMAp = temp_LMAp %>% exp) %>%
  mutate(LMAs = temp_LMAs %>% exp) %>%
  mutate(preLL = temp_LL) 

tmp <- GL %>%
  dplyr::select(sp, DE) 

d <- read_csv("./data/nature02403-s2.csv", skip = 10)

dd <- data.frame(Narea = 10^d$`log Narea`,
        Parea = 10^d$`log Parea`,
        sp = d$Species) %>%
        group_by(sp) %>%
        summarize(Narea = mean(Narea, na.omit = T),
            Parea = mean(Parea, na.omit = T))

GL <- left_join(GL, dd, by = "sp") %>%
  mutate(gr = factor(DE,
    labels = c("Deciduous",
               "Evergreen",
               "Unclassified"
                      ))) %>%
  arrange(desc(gr))

```
# Trait correlations

## A~area~, R~area~, LL

Open symbols indicate sun leaves and closed symbols indicate shade leaves. The results look nice and do not alter main conclusions.

```{r, echo = F, message = F}

GL2 <- GL %>%
  gather(LMA, val, c("LMA", "LMAp", "LMAs")) %>%
  gather(trait, val2, c("Aarea", "LL", "Rarea")) 

GL3 <- GL %>%
  gather(LMA, val, c("LMA", "LMAp", "LMAs")) %>%
  #gather(trait, val2, c("Aarea", "LL", "Rarea")) %>%
  gather(trait2, val3, c("Narea","Parea")) 

fills <- c("Deciduous" = settings$fills$D,
          "Evergreen" = settings$fills$E,
          "Unclassified" = settings$fills$U)

cols <- c("Deciduous" = settings$colors$D,
          "Evergreen" = settings$colors$E,
          "Unclassified" = settings$colors$U)

ggplot(GL2, aes(x = val, y = val2, fill = gr, col = gr)) +
  geom_point(shape = 21) +
  facet_grid(trait ~ LMA, scale = "free") +
  xlab("LMA") +
  ylab("Traits") +
  scale_fill_manual(values = fills) +
  scale_colour_manual(values = cols) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))


```


##  N~area~, P~area~

```{r, echo = F, message = F}


ggplot(GL3, aes(x = val, y = val3, fill = gr, col = gr)) +
  geom_point(shape = 21) +
  facet_grid(trait2 ~ LMA, scale = "free") +
  xlab("LMA") +
  ylab("Traits") +
  scale_fill_manual(values = fills) +
  scale_colour_manual(values = cols) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))

cor.test(log(GL$LMA), log(GL$Narea))

cor.test(log(GL$LMAp), log(GL$Narea))


```

## LMAp vs LMAs

```{r, echo = F, message = F}


ggplot(GL, aes(x = LMAp, y = LMAs, fill = gr, col = gr)) +
  geom_point(shape = 21) +
  xlab("LMAm") +
  ylab("LMAs") +
  scale_fill_manual(values = fills) +
  scale_colour_manual(values = cols) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))


cor.test(log(GL$LMAp) , log(GL$LMAs))

```

## Trait means

The results look nice and do not alter main conclusions.

```{r, echo = F, message = F}


ggplot(GL2, aes(x = gr, y = val,
                fill = gr,
                col = gr)) +
  geom_boxplot() +
  facet_grid(.~LMA, scale = "free") +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_fill_manual(values = fills) +
  scale_colour_manual(values = cols) 


```

# Pairwise cor for all randomized data

```{r}
get_GL <- function(x) {
  summary_GL_LDL <- rand_res$summary[[x]]

  summary_GL_LDL %>% 
    round(3) %>%
    DT::datatable(.)

  temp <- rand_dat$data[[1]] 

  GL0 <- dat %>%
    as_tibble %>%
    dplyr::select(sp, DE, GF)

  GL <- tibble(LMA = temp$LMA,
                   Aarea = temp$A,
                   LL = temp$LL,
                   Rarea = temp$R)

  GL <- bind_cols(GL0, GL)


#P_vec <- paste("p[", 1:nrow(GL), "]", sep = "")
  LMAp_vec <- paste("log_LMAp[", 1:nrow(GL), "]", sep = "")
  LMAs_vec <- paste("log_LMAs[", 1:nrow(GL), "]", sep = "")
  mu2_vec <- paste("Mu[", 1:nrow(GL), ",2]", sep = "")
#Mu_vec <- paste("mu[", 1:nrow(GL), ",2]", sep = "")
  temp_LMAp <- summary_GL_LDL[LMAp_vec, "mean"] 
  temp_LMAs <- summary_GL_LDL[LMAs_vec, "mean"] 
  temp_LL <- exp(summary_GL_LDL[mu2_vec, "mean"])

  GL <- GL %>%
    mutate(LMAp = temp_LMAp %>% exp) %>%
    mutate(LMAs = temp_LMAs %>% exp) %>%
    mutate(preLL = temp_LL) 

  tmp <- GL %>%
    dplyr::select(sp, DE) 

  d <- read_csv("./data/nature02403-s2.csv", skip = 10)

  dd <- data.frame(Narea = 10^d$`log Narea`,
          Parea = 10^d$`log Parea`,
          sp = d$Species) %>%
          group_by(sp) %>%
          summarize(Narea = mean(Narea, na.omit = T),
              Parea = mean(Parea, na.omit = T))

  GL <- left_join(GL, dd, by = "sp") %>%
    mutate(gr = factor(DE,
      labels = c("Deciduous",
                 "Evergreen",
                 "Unclassified"
                        ))) %>%
    arrange(desc(gr))

}

GL_list <- 1:9 %>%
  map(get_GL)

rand_nd <- tibble(rand = 1:9) %>%
  mutate(data = GL_list)

rand_nd %>%
  mutate(LL_LMAs = map_dbl(data, ~ cor(.$LL, .$LMAs))) %>%
  mutate(LL_LMAp = map_dbl(data, ~ cor(.$LL, .$LMAp))) %>%
  mutate(Aarea_LMAs = map_dbl(data, ~ cor(.$Aarea, .$LMAs))) %>%
  mutate(Aarea_LMAp = map_dbl(data, ~ cor(.$Aarea, .$LMAp))) %>%
  mutate(Rarea_LMAs = map_dbl(data, ~ cor(.$Rarea, .$LMAs))) %>%
  mutate(Rarea_LMAp = map_dbl(data, ~ cor(.$Rarea, .$LMAp))) 

```
