```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE,
                      message=FALSE)
```

```{r}

library(rstan)
library(loo)
library(mvtnorm)
library(ggthemes)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

theme_set(theme_solarized(light=F))

set.seed(123)
n <- 100

LMA <- rlnorm(n, log(80), 0.8)
p <- rbeta(n, 2, 4)


LMAp <- LMA * p
LMAs <- LMA * (1-p)
X <- cbind(1, log(LMAp), log(LMAs))
X2 <- cbind(1, (LMAp), (LMAs))
apply(X, 2, sd)
apply(X2, 2, sd)

rownames(X) <- paste0("sp", 1:n)
colnames(X) <- c("intercept", "log_LMAp", "log_LMAs")

Z <- rbind(c(2, -1, -0.5),
           c(0.4, 0.2, 0.4),
           c(-0.2, 0.8, 0))

rownames(Z) <- c("intercept", "log_LMAp", "log_LMAs")
colnames(Z) <- c("A", "LL", "R")

sigma1 <- 0.3
sigma2 <- 0.6
sigma3 <- 0.4

Mu <- X %*% Z - 0.5 * c(sigma1, sigma2, sigma3)^2

rho13 <- 0.4
rho12 <- -0.6
rho23 <- -0.6
Sigma <- matrix(c(sigma1^2, rho12*sigma1*sigma2, rho13*sigma1*sigma3,
    rho12*sigma1*sigma2, sigma2^2, rho23*sigma2*sigma3,
    rho13*sigma1*sigma3, rho23*sigma2*sigma3, sigma3^2), ncol =3)

Y <- NULL

for (i in 1:n) {
  mu <- rmvnorm(1, Mu[i,], Sigma)
  Y <- rbind(Y, mu)
}

rownames(Y) <- rownames(Mu)
colnames(Y) <- colnames(Mu)

dat <- as_data_frame(Y) %>% exp

dat2 <- dat %>%
  mutate(LMA = LMA,
         LMAp = LMAp,
         LMAs = LMAs) %>%
  gather(trait, val, 1:3) %>%
  gather(LMA, val2, 1:3)

ggplot(dat2, aes(x = log(val2), y = log(val))) +
  geom_point() +
  facet_grid(trait ~ LMA, scales = "free")

```

```{r, message = F, eval = T}

list_dat <- list(N = n,
                  A = dat$A,
                  LL = dat$LL,
                  R = dat$R,
                  LMA = LMA,
                  gr = rep(1, n),
                  J = 1)

n_iter <- 3000
n_warm <- 2000
n_thin <- 1
n_chains <- 8

writeLines(readLines("./model/latent_model.stan"))
res1 <- stan(file = "./model/latent_model.stan",
        data = list_dat,
        iter = n_iter,
        warmup = n_warm,
        thin = n_thin,
        chains = n_chains,
        control = list(adapt_delta = 0.99, max_treedepth = 20))

save.image("fake_latent_model.rda")

#load("./data/test_latent.rda")
#load("./data/test_latent_rep.rda")

```

```{r}

load("fake_latent_model.rda")

#load("./data/test_latent.rda")
#load("./data/test_latent_rep.rda")

summary1 <- data.frame(summary(res1)$summary) %>%
  round(3)

DT::datatable(summary1)

pairs(res1, pars = c("Z[1,1]", "Z[2,1]", "Z[3,1]", "lp__"))
pairs(res1, pars = c("Z[1,2]", "Z[2,2]", "Z[3,2]", "lp__"))
pairs(res1, pars = c("Z[1,3]", "Z[2,3]", "Z[3,3]", "lp__"))

traceplot(res1, pars = "Z")
#traceplot(res1, pars = c("am","as"))
traceplot(res1, pars = c("p[1]",
                        "p[2]",
                        "p[3]",
                        "lp__"
                        ))
traceplot(res1, pars = "L_Omega")


```

```{r}

par_fun <- function(x) as.data.frame(extract(res1, permuted=FALSE)[,x,])

par_dat <- map(1:n_chains, par_fun)
Z31 <- function(x) x$`Z[2,1]`
Z21 <- function(x) x$`Z[3,1]`
p1 <- function(x) x$`p[1]`

fig_dat <- data_frame(chain = 1:n_chains) %>%
  mutate(p1 = lapply(par_dat, p1)) %>%
  mutate(Z21 = lapply(par_dat, Z21)) %>%
  mutate(Z31 = lapply(par_dat, Z31)) %>%
  unnest

ggplot(fig_dat, aes(x = Z21, y = Z31, col = as.factor(chain))) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)

ggplot(fig_dat, aes(x = Z21, y = p1, col = as.factor(chain))) +
  geom_point()

pp <- extract(res1, par = "p")[[1]]

fig_dat2 <- data_frame(
  p_mid = pp %>% apply(., 2, median),
  p_up = pp %>% apply(., 2, function(x)quantile(x,0.975)) ,
  p_lo = pp %>% apply(., 2, function(x)quantile(x,0.025)),
  p_true = p
                       ) 


ggplot(fig_dat2, aes(x = p_true, y = p_mid)) +
  geom_point() +
  geom_abline(slope=1) +
  geom_errorbar(aes(ymin=p_lo, ymax=p_up))


```

```{r}

fit <- res1
mcmc_res <- extract(fit) %>% as.data.frame
params1 <- as.data.frame(extract(fit, permuted=FALSE)[,1,])
params2 <- as.data.frame(extract(fit, permuted=FALSE)[,2,])
params3 <- as.data.frame(extract(fit, permuted=FALSE)[,3,])
params4 <- as.data.frame(extract(fit, permuted=FALSE)[,4,])

plot(params1$`Z[2,1]`, params3$`Z[2,1]`)

get_stancode(fit) %>% cat

re_am <- c(params1$`Z[3,1]`,
	 			 params2$`Z[2,1]`,
	 			 params3$`Z[2,1]`,
	 			 params4$`Z[3,1]`)

re_as <- c(params1$`Z[2,1]`,
	 			 params2$`Z[3,1]`,
	 			 params3$`Z[3,1]`,
	 			 params4$`Z[2,1]`)

re_bm <- c(params1$`Z[3,2]`,
	 			 params2$`Z[2,2]`,
         params3$`Z[2,2]`,
         params4$`Z[3,2]`)

re_bs <- c(params1$`Z[2,2]`,
           params2$`Z[3,2]`,
           params3$`Z[3,2]`,
           params4$`Z[2,2]`)

re_rm <- c(params1$`Z[3,3]`,
	 			 params2$`Z[2,3]`,
         params3$`Z[2,3]`,
         params4$`Z[3,3]`)

re_rs <- c(params1$`Z[2,3]`,
           params2$`Z[3,3]`,
           params3$`Z[3,3]`,
           params4$`Z[2,3]`)

re_p1 <- c(1-params1$`p[1]` ,
          params2$`p[1]` ,
          params3$`p[1]` ,
          1-params4$`p[1]` )

re_p0 <- c(1 - params1[,paste0("p[",1:198,"]")],
  params2[,paste0("p[",1:198,"]")],
  params3[,paste0("p[",1:198,"]")],
  1 - params4[,paste0("p[",1:198,"]")]) %>% unlist 

re_p <- array(NA, 
              dim = c(4000, 198))

mpc <- fit@sim$iter-fit@sim$warmup

tmp <- array(c(re_am,
               re_as,
               re_bm,
               re_bs,
               re_rm,
               re_rs
                  ),
             dim = c(mpc * 4, 6))

tmp2 <- tmp

#par(mfrow=c(5,5))
for (i in 1:198) {
  re_p0 <- c(1 - params1[,paste0("p[",i,"]")],
    params2[,paste0("p[",i,"]")],
    params3[,paste0("p[",i,"]")],
    1 - params4[,paste0("p[",i,"]")]) 
 # hist(re_p0)
  tmp2 <- cbind(tmp2, re_p0)
}
par(mfrow=c(1,1))

amu <- array(NA,dim = c(mpc,fit@sim$chains,dim(tmp2)[2]))
for (cc in 1:fit@sim$chains) amu[,cc,] = tmp2[(1:mpc)+(cc-1)*mpc,]
mmu <- monitor(amu, print = F, warmup = 0)
rownames(mmu) <- c("am", "as", "bm", "bs", "rm", "rs", 
                   paste0("p",1:198))

mmu %>% DT::datatable(.)

mcmc_re <- data_frame(alpha_m = amu[,,1] %>% as.vector,
             alpha_s = amu[,,2] %>% as.vector,
             beta_m = amu[,,3] %>% as.vector,
             beta_s = amu[,,4] %>% as.vector,
             gamma_m = amu[,,5] %>% as.vector,
             gamma_s = amu[,,6] %>% as.vector
             ) %>%
  mutate(iter = rep(1:1000, 4)) %>%
  mutate(chain = rep(1:4, each = 1000) %>% as.factor)

mcmc_re2 <- mcmc_re %>%
  gather(para, val, 1:6)

ggplot(mcmc_re2, aes(x = iter, y = val, col = chain)) +
  geom_line() +
  facet_wrap(~para)

```

