---
title: GLOPNET results
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

- alpha_0 LMAm^alpha_p 
- beta_0 LMAs^beta_s


```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE,
                      message=FALSE)
```


```{r, echo = F, message = F}
library(loo)
library(rstan)
library(dplyr)
library(scales)
library(memisc)

theme_set(theme_light())

settings <- yaml::yaml.load_file("settings.yml")
```


```{r, echo = F, message = F}

#load("./data/PA_sitePL_LD_L_MVN_obs.rda")
load("./data/GL_m0_obs.rda")


#summary_PA_LDL <- data.frame(summary(res)$summary)

summary_GL_LDL <- data.frame(summary(res)$summary)

GL <- dat %>%
  as_data_frame 


P_vec <- paste("p[", 1:nrow(GL), "]", sep = "")
mu2_vec <- paste("mu2[", 1:nrow(GL), "]", sep = "")
#Mu_vec <- paste("mu[", 1:nrow(GL), ",2]", sep = "")
temp_LMAp <- summary_GL_LDL[P_vec, "mean"] * GL$LMA
temp_LMAs <- GL$LMA - temp_LMAp
temp_LL <- exp(summary_GL_LDL[mu2_vec, "mean"])

#ap <- rstan::extract(res, "beta[2]")[[1]]
#temp_LMAp <- median(ap) * temp_LMAm

GL <- GL %>%
  mutate(LMAp = temp_LMAp) %>%
  mutate(LMAs = temp_LMAs) %>%
  mutate(preLL = temp_LL) 

d <- read_csv("./data/nature02403-s2.csv", skip = 10)

dd <- data.frame(Narea = 10^d$`log Narea`,
        Parea = 10^d$`log Parea`,
        sp = d$Species) %>%
        group_by(sp) %>%
        summarize(Narea = mean(Narea, na.omit = T),
            Parea = mean(Parea, na.omit = T))

GL <- left_join(GL, dd, by = "sp") %>%
  mutate(gr = factor(DE,
    labels = c("Deciduous",
               "Evergreen",
               "Unclassified"
                      ))) %>%
  arrange(desc(gr))

GL2 <- GL %>%
  arrange(LMA) %>%
  gather(LMA2, val, c("LMAp", "LMAs")) %>%
  mutate(ordering = 1:nrow(.)) %>%
  mutate(sp2 = fct_reorder(sp, ordering))


```


```{r, echo = F, message = F}

load("./data/PA_m1q_more_obs.rda")
summary_PA_LDL <- data.frame(summary(res)$summary)

PA <- dat %>%
  as_data_frame %>%
  mutate(site2 = ifelse(site == "PNM", "DRY", "WET")) %>%
  mutate(sp_site_strata = paste(sp, site2, strata, sep = "_")) %>%
  mutate(site_strata = paste(site2, strata, sep = "_"))


P_vec <- paste("p[", 1:nrow(PA), "]", sep = "")
mu2_vec <- paste("mu2[", 1:nrow(PA), "]", sep = "")
#Mu_vec <- paste("mu[", 1:nrow(PA), ",2]", sep = "")
temp_LMAp <- summary_PA_LDL[P_vec, "mean"] * PA$LMA
temp_LMAs <- PA$LMA - temp_LMAp
temp_LL <- exp(summary_PA_LDL[mu2_vec, "mean"])


PA <- PA %>%
  mutate(LMAp = temp_LMAp) %>%
  mutate(LMAs = temp_LMAs) %>%
  mutate(preLL = temp_LL) %>%
  mutate(LDs = LMAs/LT/1000)


PA2 <- PA %>%
  arrange(LMA) %>%
  gather(LMA2, val, c("LMAp", "LMAs")) %>%
  mutate(ordering = 1:nrow(.)) %>%
  mutate(sp_site_strata = fct_reorder(sp_site_strata, ordering)) 


```



```{r, message = F}

ggplot(GL2, aes(x = sp2, y = val, fill = LMA2)) +
  geom_col() +
  ylab("LMA value") +
  xlab("GLOPNET species") 

ggplot(PA2, aes(x = sp_site_strata, y = val, fill = LMA2)) +
  geom_col() +
  ylab("LMA value") +
  xlab("Panama species") 

ggplot(GL2, aes(x = sp2, y = val, fill = LMA2)) +
  geom_col() +
  ylab("LMA value") +
  xlab("GLOPNET species") +
  facet_grid(~DE)

ggplot(PA2, aes(x = sp_site_strata, y = val, fill = LMA2)) +
  geom_col() +
  ylab("LMA value") +
  xlab("Panama species")  +
  facet_grid(site~strata)


```

```{r, echo = F}

var_p <- function(data)cov(data$LMA, data$LMAp)
var_s <- function(data)cov(data$LMA, data$LMAs)
var_t <- function(data)var(data$LMA)

var_p <- function(data)var(data$LMAp)
var_s <- function(data)var(data$LMAs)
cov_ps <- function(data)cov(data$LMAp, data$LMAs)
var_t <- function(data)var(data$LMA)

var_dat <- GL %>%
  mutate(site = "GL") %>%
  group_by(site) %>%
  nest %>%
  mutate(var_LMAm = map_dbl(data, var_p)) %>%
  mutate(var_LMAs = map_dbl(data, var_s)) %>%
  mutate(cov_ms = 2 * map_dbl(data, cov_ps)) %>%
  mutate(var_total = map_dbl(data, var_t)) %>%
  dplyr::select(-data)

var_dat_s <- var_dat %>%
  mutate(LMAm_variance = var_LMAm / (var_LMAm + var_LMAs) * 100) %>%
  mutate(LMAs_variance = var_LMAs / (var_LMAm + var_LMAs) * 100) %>%
  gather(var, val, c(LMAm_variance, LMAs_variance))

var_dat_s2 <- var_dat %>%
  mutate(LMAm_variance = var_LMAm / (var_total) * 100) %>%
  mutate(LMAs_variance = var_LMAs / (var_total) * 100) %>%
  mutate(cov_LMAm_LMAs = cov_ms / (var_total) * 100) %>%
  gather(var, val, c(LMAm_variance, LMAs_variance, cov_LMAm_LMAs)) 


```

# Decomposition of LMA variation 

1) var(LMAm) & var(LMAs) & 2*cov(LMAm, LMAs), 2)relative contribution: var(LMAm)/(var(LMAm) + var(LMAs)) & var(LMAs) /(var(LMAm) + var(LMAs))

```{r, echo = F}

ggplot(var_dat_s2, aes(x = site, y = val, fill = var)) +
  geom_col() +
  ylab("val (%)") 

ggplot(var_dat_s, aes(x = site, y = val, fill = var)) +
  geom_bar(position = "fill",stat = "identity") +
  scale_y_continuous(labels = percent_format())

GL

summary_GL_LDL %>% tail


lm(log(Aarea) ~ log(LMA), GL) %>% summary

```

