## Model estimation

We used independent and weakly- and non-informative prior distributions for all parameters, including latent variables *f~ik~* for each leaf sample. The covariance matrix in Eq.@ref(eq:MVN) was decomposed as

${\boldsymbol \Sigma} = {\rm diag}(\boldsymbol \sigma){\bf \Omega}{\rm diag}(\boldsymbol \sigma) = {\rm diag}({\boldsymbol \sigma}){\bf LL}\prime {\rm diag}({\boldsymbol \sigma})$ using a Cholesky decomposition, where $\boldsymbol \sigma$ is a vector of $\sigma_{1}$, $\sigma_{2}$, and $\sigma_{3}$; $\bf {\Omega}$ is a correlation matrix of $\rho_{12}$, $\rho_{13}$, and $\rho_{23}$; and $\bf L$ is a lower triangular matrix. Instead of assigning prior distributions on directly, priors were assigned on and *L* to avoid a strong dependence between and [@Lewandowski2009; @Alvarez2014]. A prior for $\bf L$ was specified as a so-called LKJ distribution with shape parameter 1 [@Lewandowski2009], which is identical to a uniform distribution on the space of correlation matrices. Priors for $\boldsymbol \sigma$ were specified as half-Cauchy distributions with location 0 and scale 5. Priors for $log\, \alpha_0$, $log\, \beta_0$, $log\, \gamma_0$, $\alpha_i$, $\beta_i$ and $\gamma_i$ were specified as normal distributions with mean 0 and variance 10. For the Panama data, we also used the repulsive priors with $\nu = 2$ introduced by [@Petralia2012] to keep $\alpha_m$ and $\alpha_s$ well-separated. Priors for *f~i~* in Eqs. 4-6 and 8 were specified as uniform distributions with range (0, 1).

Posterior distributions of all parameters were estimated using the Hamiltonian Monte Carlo algorithm (HMC) implemented in Stan [@Carpenter2017]. See supplement X for more detail. The Stan code use to fit models are also available from Github at: [https://github.com/mattocci27/LMAmLMAs](https://github.com/mattocci27/LMAmLMAs). Some parameters are exchangeable in our model. For example, $(f_i, \ \alpha_m, \ \alpha_s)$ = (0.2, 0.5, 1.0) and (0.8, 1.0, 0.5) yield the identical likelihood, which results in bimodal distributions of the posterior distributions of parameters (See X). To avoid this non-identifiability, i) we simply switched labels so that $\alpha_m$ > $\alpha_s$ (LMAm is associated with metabolic rates by our definition) or ii) we constrained  $\alpha_m$ > $\alpha_s$. Both methods yield qualitatively similar results and we report the second method for the main text. Convergence of the posterior distribution was assessed with the Gelman-Rubin statistic with a convergence threshold of 1.1 for all diagnostics [@Gelman2014].

Because our statistical approach includes one latent variable *f~i~* to partition LMA into LMAm and LMAs for each leaf sample, one might expect a good match between predictions and observations simply due to the large number of free parameters, whether or not the model captured important biological mechanisms. However, the same models applied to randomly shuffled observe dataset did not produce any significant patterns (Supplement X). Thus, we assume that estimates of LMAm and LMAs reflect meaningful pattens in the data.
