---
title: "GL"
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE,
                      message=FALSE)
```

```{r caching, include=FALSE}
library(methods)
library(knitr)
library(kableExtra)
```


```{r}
library(tidyverse)
library(rstan)
library(stringr)
library(loo)
rstan_options(auto_write = TRUE)
# options(mc.cores = parallel::detectCores())
options(mc.cores = 3)

set.seed(5)

n_chains <- 3

dat <- read_csv("./data/GL_data.csv") %>%
    mutate(DE = ifelse(is.na(DE), "U", DE)) %>%
    as.data.frame

list_dat <- list(n_sample = nrow(dat),
                 #obs = cbind(log(dat[ , "Aarea"] + dat[ , "Rarea"]),
                 obs = cbind(log(dat[ , "Aarea"]),
                             log(dat[ , "LL"]),
                             log(dat[ , "Rarea"])),
                 LMA = dat[ , "LMA"],
                 A = dat[ , "Aarea"],
                 R = dat[ , "Rarea"],
                 q_lim = 1,
                 leaf = 1,
                 dry = 1,
                 DE = as.numeric(as.factor(dat$DE)))


list_dat2 <- list_dat
list_dat2$obs <- cbind(log(dat[ , "Aarea"] + dat[, "Rarea"]),
                             log(dat[ , "LL"]),
                             log(dat[ , "Rarea"]))


modelMVN <- "
  data{
    int<lower=0> n_sample;
    vector<lower=0>[n_sample] LMA;
    row_vector[3] obs[n_sample];
  }
  parameters{
    vector[7] beta;
    vector<lower=0>[3] sigma;
    cholesky_factor_corr[3] L_Omega;
    vector<lower=0, upper=1>[n_sample] p;
  }
  transformed parameters{
    row_vector[3] mu[n_sample];
    for (i in 1:n_sample){
      mu[i,1] = beta[1] + beta[2] * (log(LMA[i]) + log(p[i]))
            - 0.5 * square(sigma[1]);
      mu[i,2] = beta[3] + beta[4] * (log(LMA[i]) + log(1-p[i]))
             - 0.5 * square(sigma[2]);
      mu[i,3] = beta[5] +  beta[6] * (log(LMA[i]) + log(p[i]))
              + beta[7] * (log(LMA[i]) + log(1-p[i]))
               - 0.5 * square(sigma[3]);
    }
  }
  model{
    obs ~ multi_normal_cholesky(mu, diag_pre_multiply(sigma, L_Omega));
    beta ~ normal(0, 10);
    p ~ uniform(0, 1);
    sigma ~ cauchy(0, 5);
    L_Omega ~ lkj_corr_cholesky(1); //uniform of L_Omega * L_Omega'
  }
  generated quantities {
    vector[n_sample] log_lik;
    real<lower=-1, upper=1> rho12;
    real<lower=-1, upper=1> rho23;
    real<lower=-1, upper=1> rho13;
    cov_matrix[3] Sigma;
    Sigma = diag_pre_multiply(sigma, L_Omega)
       * diag_post_multiply(L_Omega', sigma);
    rho12 = Sigma[1, 2] * inv(sigma[1] * sigma[2]);
    rho23 = Sigma[2, 3] * inv(sigma[2] * sigma[3]);
    rho13 = Sigma[1, 3] * inv(sigma[1] * sigma[3]);
    for (i in 1:n_sample)
     log_lik[i] = multi_normal_cholesky_lpdf(obs[i] | mu[i], diag_pre_multiply(sigma, L_Omega));
   }
"


modelN <- "
  data{
    int<lower=0> n_sample;
    vector<lower=0>[n_sample] LMA;
    vector[3] obs[n_sample];
  }
  parameters{
    vector[7] beta;
    vector<lower=0>[3] sigma;
    vector<lower=0, upper=1>[n_sample] p;
  }
  transformed parameters{
    vector[3] mu[n_sample];
    for (i in 1:n_sample){
      mu[i,1] = beta[1] + beta[2] * (log(LMA[i]) + log(p[i]))
            - 0.5 * square(sigma[1]);
      mu[i,2] = beta[3] + beta[4] * (log(LMA[i]) + log(1-p[i]))
             - 0.5 * square(sigma[2]);
      mu[i,3] = beta[5] +  beta[6] * (log(LMA[i]) + log(p[i]))
              + beta[7] * (log(LMA[i]) + log(1-p[i]))
               - 0.5 * square(sigma[3]);
    }
  }
  model{
    for (i in 1:n_sample) {
      obs[i,1] ~ normal(mu[i,1], sigma[1]);
      obs[i,2] ~ normal(mu[i,2], sigma[2]);
      obs[i,3] ~ normal(mu[i,3], sigma[3]);
    }
    beta ~ normal(0, 10);
    p ~ uniform(0, 1);
    sigma ~ cauchy(0, 5);
  }
  generated quantities {
    vector[n_sample] log_lik;
    vector[n_sample] log_lik1;
    vector[n_sample] log_lik2;
    vector[n_sample] log_lik3;
    for (i in 1:n_sample){
     log_lik1[i] = normal_lpdf(obs[i, 1] | mu[i, 1], sigma[1]);
     log_lik2[i] = normal_lpdf(obs[i, 2] | mu[i, 2], sigma[2]);
     log_lik3[i] = normal_lpdf(obs[i, 3] | mu[i, 3], sigma[3]);
   }
    log_lik = log_lik1 + log_lik2 + log_lik3;
  }
"

modelMVNH <- "
  data{
    int<lower=0> n_sample;
    vector<lower=0>[n_sample] LMA;
    row_vector[3] obs[n_sample];
    int DE[n_sample];
  }
  parameters{
    vector[7] beta[3];
    vector[7] beta_hat;
    vector<lower=0>[7] sigma_beta;
    vector<lower=0>[3] sigma;
    cholesky_factor_corr[3] L_Omega;
    vector<lower=0, upper=1>[n_sample] p;
  }
  transformed parameters{
    row_vector[3] mu[n_sample];
    for (i in 1:n_sample){
      mu[i,1] = beta[DE[i], 1] + beta[DE[i], 2] * (log(LMA[i]) + log(p[i]))
            - 0.5 * square(sigma[1]);
      mu[i,2] = beta[DE[i], 3] + beta[DE[i], 4] * (log(LMA[i]) + log(1-p[i]))
             - 0.5 * square(sigma[2]);
      mu[i,3] = beta[DE[i], 5] +  beta[DE[i], 6] * (log(LMA[i]) + log(p[i]))
              + beta[DE[i], 7] * (log(LMA[i]) + log(1-p[i]))
               - 0.5 * square(sigma[3]);
    }
  }
  model{
    obs ~ multi_normal_cholesky(mu, diag_pre_multiply(sigma, L_Omega));
    for (i in 1:3){
      beta[i] ~ normal(beta_hat, sigma_beta[i]);
    }
    beta_hat ~ normal(0, 10);
    sigma_beta ~ cauchy(0, 5);
    p ~ uniform(0, 1);
    sigma ~ cauchy(0, 5);
    L_Omega ~ lkj_corr_cholesky(1); //uniform of L_Omega * L_Omega'
  }
  generated quantities {
    vector[n_sample] log_lik;
    real<lower=-1, upper=1> rho12;
    real<lower=-1, upper=1> rho23;
    real<lower=-1, upper=1> rho13;
    cov_matrix[3] Sigma;
    Sigma = diag_pre_multiply(sigma, L_Omega)
       * diag_post_multiply(L_Omega', sigma);
    rho12 = Sigma[1, 2] * inv(sigma[1] * sigma[2]);
    rho23 = Sigma[2, 3] * inv(sigma[2] * sigma[3]);
    rho13 = Sigma[1, 3] * inv(sigma[1] * sigma[3]);
    for (i in 1:n_sample)
     log_lik[i] = multi_normal_cholesky_lpdf(obs[i] | mu[i], diag_pre_multiply(sigma, L_Omega));
   }
"


modelNH <- "
  data{
    int<lower=0> n_sample;
    vector<lower=0>[n_sample] LMA;
    vector[3] obs[n_sample];
    int DE[n_sample];
  }
  parameters{
    vector[7] beta[3];
    vector[7] beta_hat;
    vector<lower=0>[3] sigma;
    vector<lower=0>[7] sigma_beta;
    vector<lower=0, upper=1>[n_sample] p;
  }
  transformed parameters{
    vector[3] mu[n_sample];
    for (i in 1:n_sample){
      mu[i,1] = beta[DE[i], 1] + beta[DE[i], 2] * (log(LMA[i]) + log(p[i]))
            - 0.5 * square(sigma[1]);
      mu[i,2] = beta[DE[i], 3] + beta[DE[i], 4] * (log(LMA[i]) + log(1-p[i]))
             - 0.5 * square(sigma[2]);
      mu[i,3] = beta[DE[i], 5] +  beta[DE[i], 6] * (log(LMA[i]) + log(p[i]))
              + beta[DE[i], 7] * (log(LMA[i]) + log(1-p[i]))
               - 0.5 * square(sigma[3]);
    }
  }
  model{
    for (i in 1:n_sample) {
      obs[i,1] ~ normal(mu[i,1], sigma[1]);
      obs[i,2] ~ normal(mu[i,2], sigma[2]);
      obs[i,3] ~ normal(mu[i,3], sigma[3]);
    }
    for (i in 1:3){
      beta[i] ~ normal(beta_hat, sigma_beta[i]);
    }
    beta_hat ~ normal(0, 10);
    sigma_beta ~ cauchy(0, 5);
    p ~ uniform(0, 1);
    sigma ~ cauchy(0, 5);
  }
  generated quantities {
    vector[n_sample] log_lik;
    vector[n_sample] log_lik1;
    vector[n_sample] log_lik2;
    vector[n_sample] log_lik3;
    for (i in 1:n_sample){
     log_lik1[i] = normal_lpdf(obs[i, 1] | mu[i, 1], sigma[1]);
     log_lik2[i] = normal_lpdf(obs[i, 2] | mu[i, 2], sigma[2]);
     log_lik3[i] = normal_lpdf(obs[i, 3] | mu[i, 3], sigma[3]);
   }
    log_lik = log_lik1 + log_lik2 + log_lik3;
  }
"


```

# MVN + A

```{r, eval = FALSE}
n_iter <- 1000
n_warm <- 500
n_thin <- 1

system.time(fit <- stan(model_code = modelMVN,
            data = list_dat,
            iter = 1,
            warmup = 0,
            thin = 1,
            chains = 1))

system.time(res <- stan(fit = fit,
           data = list_dat,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

summary1 <- data.frame(summary(res)$summary)

head(summary1, 10)
tail(summary1, 10)

```


# MVN + AR

```{r, eval = FALSE}

system.time(res2 <- stan(fit = fit,
           data = list_dat2,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

summary2 <- data.frame(summary(res2)$summary)

head(summary2, 10)
tail(summary2, 10)
```


# N + A

```{r, eval = FALSE}
system.time(fit <- stan(model_code = modelN,
            data = list_dat,
            iter = 1,
            warmup = 0,
            thin = 1,
            chains = 1))

system.time(res3 <- stan(fit = fit,
           data = list_dat,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

summary3 <- data.frame(summary(res3)$summary)

head(summary3, 10)
tail(summary3, 10)

```

# N + AR

```{r, eval = FALSE}

system.time(res4 <- stan(fit = fit,
           data = list_dat2,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

summary4 <- data.frame(summary(res4)$summary)

head(summary4, 10)
tail(summary4, 10)


```

# MVN + A + H

```{r, eval = FALSE}

system.time(fit <- stan(model_code = modelMVNH,
            data = list_dat,
            iter = 1,
            warmup = 0,
            thin = 1,
            chains = 1))

system.time(res5 <- stan(fit = fit,
           data = list_dat,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

summary5 <- data.frame(summary(res5)$summary)

head(summary5, 10)
tail(summary5, 10)

```

# MVN + A + H

```{r, eval = FALSE}


system.time(res6 <- stan(fit = fit,
           data = list_dat2,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

summary6 <- data.frame(summary(res6)$summary)

head(summary6, 10)
tail(summary6, 10)

```

# N + A + H

```{r, eval = FALSE}

system.time(fit <- stan(model_code = modelNH,
            data = list_dat,
            iter = 1,
            warmup = 0,
            thin = 1,
            chains = 1))

system.time(res7 <- stan(fit = fit,
           data = list_dat,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

summary7 <- data.frame(summary(res7)$summary)

head(summary7, 22)
tail(summary7, 10)

```

# N + AR + H

```{r, eval = FALSE}


system.time(res8 <- stan(fit = fit,
           data = list_dat2,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

summary8 <- data.frame(summary(res8)$summary)

head(summary8, 22)
tail(summary8, 10)

#save.image("GL_test.rda")

```

# Posterior distribution


```{r, echo = F}

load("GL_test.rda")

par1 <- extract(res, par = c("beta", "sigma", "rho12","rho23","rho13", "p[1]"))
par2 <- extract(res2, par = c("beta", "sigma", "rho12","rho23","rho13", "p[1]"))
par3 <- extract(res3, par = c("beta", "sigma", "p[1]"))
par4 <- extract(res4, par = c("beta", "sigma", "p[1]"))

par5 <- extract(res5, par = c("beta_hat", "sigma", "rho12","rho23","rho13", "p[1]"))
par6 <- extract(res6, par = c("beta_hat", "sigma", "rho12","rho23","rho13", "p[1]"))
par7 <- extract(res7, par = c("beta_hat", "sigma", "p[1]"))
par8 <- extract(res8, par = c("beta_hat", "sigma", "p[1]"))

par_dat1 <- data_frame(par = c("beta1",
                               "beta2",
                               "beta3",
                               "beta4",
                               "beta5",
                               "beta6",
                               "beta7",
                               "sigma1",
                               "sigma2",
                               "sigma3",
                               "rho12","rho23","rho13",
                               "p[1]" ) %>%
                             rep(each = 1500),
           val = unlist(par1)) %>%
  mutate(dat = "MVN_A")

par_dat2 <- data_frame(par = c("beta1",
                               "beta2",
                               "beta3",
                               "beta4",
                               "beta5",
                               "beta6",
                               "beta7",
                              "sigma1",
                              "sigma2",
                              "sigma3",
                              "rho12","rho23","rho13",
                               "p[1]") %>%
                             rep(each = 1500),
           val = unlist(par2)) %>%
  mutate(dat = "MVN_AR")

par_dat3 <- data_frame(par = c("beta1",
                               "beta2",
                               "beta3",
                               "beta4",
                               "beta5",
                               "beta6",
                               "beta7",
                               "sigma1",
                               "sigma2",
                               "sigma3",
                               "p[1]") %>%
                            rep(each = 1500),
           val = unlist(par3)) %>%
  mutate(dat = "N_A")

par_dat4 <- data_frame(par = c("beta1",
                               "beta2",
                               "beta3",
                               "beta4",
                               "beta5",
                               "beta6",
                               "beta7",
                               "sigma1",
                               "sigma2",
                               "sigma3",
                               "p[1]") %>%
                            rep(each = 1500),
           val = unlist(par4)) %>%
  mutate(dat = "N_AR")

par_dat5 <- data_frame(par = c("beta1",
                               "beta2",
                               "beta3",
                               "beta4",
                               "beta5",
                               "beta6",
                               "beta7",
                               "sigma1",
                               "sigma2",
                               "sigma3",
                               "rho12","rho23","rho13",
                               "p[1]" ) %>%
                             rep(each = 1500),
           val = unlist(par5)) %>%
  mutate(dat = "MVN_A_H")

par_dat6 <- data_frame(par = c("beta1",
                               "beta2",
                               "beta3",
                               "beta4",
                               "beta5",
                               "beta6",
                               "beta7",
                              "sigma1",
                              "sigma2",
                              "sigma3",
                              "rho12","rho23","rho13",
                               "p[1]") %>%
                             rep(each = 1500),
           val = unlist(par6)) %>%
  mutate(dat = "MVN_AR_H")

par_dat7 <- data_frame(par = c("beta1",
                               "beta2",
                               "beta3",
                               "beta4",
                               "beta5",
                               "beta6",
                               "beta7",
                               "sigma1",
                               "sigma2",
                               "sigma3",
                               "p[1]") %>%
                            rep(each = 1500),
           val = unlist(par7)) %>%
  mutate(dat = "N_A_H")

par_dat8 <- data_frame(par = c("beta1",
                               "beta2",
                               "beta3",
                               "beta4",
                               "beta5",
                               "beta6",
                               "beta7",
                               "sigma1",
                               "sigma2",
                               "sigma3",
                               "p[1]") %>%
                            rep(each = 1500),
           val = unlist(par8)) %>%
  mutate(dat = "N_AR_H")

par_dat <- bind_rows(par_dat1, par_dat2, par_dat3, par_dat4,
                     par_dat5, par_dat6, par_dat7, par_dat8) %>%
  mutate(model2 = ifelse(str_detect(dat,"_H$"),
                         "multi-level",
                         "single-level"))

```

## all model

```{r, echo = F}
ggplot(par_dat, aes(val, col = dat, alpha = 0.8)) +
#  geom_histogram(aes(y =..density..)) +
  geom_density() +
  facet_wrap(~par, scale = "free")
```

## multi-level models

```{r, echo = F}
ggplot(par_dat %>% filter(model2 == "multi-level"), aes(val,  col = dat, alpha = 0.8)) +
#  geom_histogram(aes(y =..density..)) +
  geom_density() +
  facet_wrap(~par, scale = "free")
```


## single-level models

```{r, echo = F}
ggplot(par_dat %>% filter(model2 == "single-level"), aes(val, col = dat, alpha = 0.8)) +
#  geom_histogram(aes(y =..density..)) +
  geom_density() +
  facet_wrap(~par, scale = "free")

```


## MVN_AR_H or H_AR

```{r, echo = F}

ggplot(par_dat %>%
       filter(dat == "MVN_AR_H" | dat == "N_AR"), aes(val, fill = dat, col = dat, alpha = 0.6)) +
#  geom_histogram(aes(y =..density..)) +
  geom_density() +
  facet_wrap(~par, scale = "free")

```


```{r, echo = F}

p1 <- extract(res, par = "p")
p1 <- apply(p1[[1]], 2, median)

p2 <- extract(res2, par = "p")
p2 <- apply(p2[[1]], 2, median)

p3<- extract(res3, par = "p")
p3 <- apply(p3[[1]], 2, median)

p4 <- extract(res4, par = "p")
p4 <- apply(p4[[1]], 2, median)

p5 <- extract(res5, par = "p")
p5 <- apply(p5[[1]], 2, median)

p6 <- extract(res6, par = "p")
p6 <- apply(p6[[1]], 2, median)

p7<- extract(res7, par = "p")
p7 <- apply(p7[[1]], 2, median)

p8 <- extract(res8, par = "p")
p8 <- apply(p8[[1]], 2, median)

GL <- dat %>%
  mutate(p1 = p1) %>%
 # mutate(LMAp1 = LMA * p1) %>%
 # mutate(LMAs1 = LMA - LMAp1) %>%
  mutate(p2 = p2) %>%
 # mutate(LMAp2 = LMA * p2) %>%
 # mutate(LMAs2 = LMA - LMAp2) %>%
  mutate(p3 = p3) %>%
 # mutate(LMAp3 = LMA * p3) %>%
 # mutate(LMAs3 = LMA - LMAp3) %>%
  mutate(p4 = p4)  %>%
 # mutate(LMAp4 = LMA * p4) %>%
 # mutate(LMAs4 = LMA - LMAp4)
  mutate(p5 = p5) %>%
  mutate(p6 = p6) %>%
  mutate(p7 = p7) %>%
  mutate(p8 = p8)

GL2 <- GL %>%
  gather(p_type, p_val, c("p1", "p2", "p3", "p4",
                          "p5", "p6", "p7", "p8")) %>%
  mutate(LMAp = LMA * p_val) %>%
  mutate(LMAs = LMA - LMAp) %>%
  mutate(model = ifelse(p_type == "p1",
                        "MVN_A",
                        p_type)) %>%
  mutate(model = ifelse(p_type == "p2",
                        "MVN_AR",
                        model)) %>%
  mutate(model = ifelse(p_type == "p3",
                        "N_A",
                        model)) %>%
  mutate(model = ifelse(p_type == "p4",
                        "N_AR",
                        model))  %>%
  mutate(model = ifelse(p_type == "p5",
                        "MVN_A_H",
                        model)) %>%
  mutate(model = ifelse(p_type == "p6",
                        "MVN_AR_H",
                        model)) %>%
  mutate(model = ifelse(p_type == "p7",
                        "N_A_H",
                        model)) %>%
  mutate(model = ifelse(p_type == "p8",
                        "N_AR_H",
                        model)) %>%
  mutate(model2 = ifelse(str_detect(model,"_H$"),
                         "multi-level",
                         "single_level"))

```

##  LMAp vs Aarea

```{r, echo = F}
ggplot(GL2, aes(x = log10(LMAp), y = log10(Aarea), col = DE, shape = model2) ) +
  geom_point() +
  facet_wrap(~model) +
  geom_smooth(method = "lm")
```


##  LMAs vs LL

```{r, echo = F}

ggplot(GL2, aes(x = log10(LMAs), y = log10(LL), col = DE, shape = model2) ) +
  geom_point() +
  facet_wrap(~model) +
  geom_smooth(method = "lm")

ggplot(GL2, aes(x = log10(LMAs), y = log10(LL), shape = model2) ) +
  geom_point() +
  facet_wrap(~model) +
  geom_smooth(method = "lm")

```

##  LMAp vs Aarea

```{r, echo = F}
ggplot(GL2, aes(x = log10(LMAp), y = log10(Rarea), col = DE, shape = model2) ) +
  geom_point() +
  facet_wrap(~model) +
  geom_smooth(method = "lm")
```

##  box plot for LMAp fraction (LMAp/LMA)

```{r, echo = F}
ggplot(GL2, aes(x = DE, y = p_val, fill = model, lty = model2) ) +
  geom_boxplot()
```

##  box plot for LMAp

```{r, echo = F}
ggplot(GL2, aes(x = DE, y = log10(LMAp), fill = model, lty = model2) ) +
  geom_boxplot()
```

##  box plot for LMAs

```{r, echo = F}
ggplot(GL2, aes(x = DE, y = log10(LMAs), fill = model, lty = model2) ) +
  geom_boxplot()
```


