---
title: "MVN"
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE,
                      message=FALSE)
```

```{r caching, include=FALSE}
library(methods)
library(knitr)
library(kableExtra)
```

## Two independent normal distibution

```{r}
library(tidyverse)
library(rstan)
library(stringr)
library(loo)
library(mvtnorm)
rstan_options(auto_write = TRUE)
# options(mc.cores = parallel::detectCores())
options(mc.cores = 3)
set.seed(5)

n <- 100
a1 <- 1.6
#a2 <- 0.28
a2 <- 0.35
b1 <- -1
b2 <- 0.88
c1 <- -1.1
#c2 <- 0.25
c2 <- 0.2
#c3 <- 0.11
c3 <- 0.2
sigma1 <- 0.4
sigma2 <- 0.3
sigma3 <- 0.3

x1 <- rnorm(n)
x2 <- rnorm(n, x1, 3) %>%
  scale %>% as.numeric

cor.test(x1, x2)

mu1 <- a1 + a2 * x1
mu2 <- b1 + b2 * x2
mu3 <- c1 + c2 * x1 + c3 * x2

a1 + c1
a2 + c2

y1 <- rnorm(n, 
            mu1 + mu3,
            sigma1)

y2 <- rnorm(n, 
            mu2,
            sigma2)

y3 <- rnorm(n, 
            mu3,
            sigma3)

dat <- data_frame(x1, x2, y1, y2, y3)

fig_dat <- dat %>%
  gather(x, x_val, 1:2) %>%
  gather(y, y_val, 1:3)

lm(y3 ~ x1 + x2, dat) %>%
  summary

ggplot(fig_dat, aes(x = x_val, y = y_val)) +
  geom_point() +
  facet_grid(y ~ x, scale = "free")

ggplot(dat, aes(x = y1, y = y2)) +
  geom_point() 


list_dat <- list(obs = cbind(dat$y1, dat$y2, dat$y3),
                 x1 = dat$x1,
                 x2 = dat$x2,
                 n_sample = n)

```

```{r}
model <- "
  data{
    int<lower=0> n_sample;
    vector[3] obs[n_sample];
    vector[n_sample] x1;
    vector[n_sample] x2;
  }
  parameters{
    real a1;
    real a2;
    real b1;
    real b2;
    real c1;
    real c2;
    real c3;
    vector<lower=0>[3] L_sigma;
    cholesky_factor_corr[3] L_Omega;
  }
  transformed parameters{
    vector[3] mu[n_sample];
    for (i in 1:n_sample){
      mu[i,1] = a1 + a2 * x1[i];
      mu[i,2] = b1 + b2 * x2[i];
      mu[i,3] = c1 + c2 * x1[i] + c3 * x2[i];
    }
  }
  model{
    obs ~ multi_normal_cholesky(mu, diag_pre_multiply(L_sigma, L_Omega));
    a1 ~ normal(0, 10);
    a2 ~ normal(0, 10);
    b1 ~ normal(0, 10);
    b2 ~ normal(0, 10);
    c1 ~ normal(0, 10);
    c2 ~ normal(0, 10);
    c3 ~ normal(0, 10);
    L_Omega ~ lkj_corr_cholesky(1); //uniform of L_Omega * L_Omega'
    L_sigma ~ cauchy(0, 5);
  }
  generated quantities {
      vector[n_sample] log_lik;
      real<lower=-1, upper=1> rho12;
      real<lower=-1, upper=1> rho23;
      real<lower=-1, upper=1> rho13;
      cov_matrix[3] Sigma;
      Sigma = diag_pre_multiply(L_sigma, L_Omega)
          * diag_post_multiply(L_Omega', L_sigma);
      rho12 = Sigma[1, 2] * inv(L_sigma[1] * L_sigma[2]);
      rho23 = Sigma[2, 3] * inv(L_sigma[2] * L_sigma[3]);
      rho13 = Sigma[1, 3] * inv(L_sigma[1] * L_sigma[3]);
      for (i in 1:n_sample) 
       log_lik[i] = multi_normal_cholesky_lpdf(obs[i] | mu[i], diag_pre_multiply(L_sigma, L_Omega));
     }
"

n_chains <- 3
n_iter <- 1000
n_warm <- 500
n_thin <- 1

system.time(fit <- stan(model_code = model,
            data = list_dat,
            iter = 1,
            warmup = 0,
            thin = 1,
            chains = 1))

system.time(res <- stan(fit = fit,
           data = list_dat,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

fit_summary <- data.frame(summary(res)$summary)

fit_summary %>% head(11) %>% print
fit_summary %>% tail %>% print


par1 <- extract(res, par = c("a1", "a2",
                     "b1", "b2",
                     "c1", "c2", "c3"))

par_dat <- data_frame(par = c("a1", "a2",
                     "b1", "b2",
                     "c1", "c2", "c3") %>% rep(each = 1500),
           val = unlist(par1)) %>%
  mutate(dat = "N")

```


## Multivariate normal distibution

```{r}

rho12 <- -0.58
rho23 <- -0.62
rho13 <- 0.55

Sigma <- matrix(c(sigma1^2, rho12*sigma1*sigma2, rho13*sigma1*sigma3,
    rho12*sigma1*sigma2, sigma2^2, rho23*sigma2*sigma3,
    rho13*sigma1*sigma3, rho23*sigma2*sigma3, sigma3^2), ncol =3)

y_new <- NULL
for (i in 1:n){
  y <- rmvnorm(1, c(mu1[i] + mu3[i], mu2[i], mu3[i]), Sigma)
  y_new <- rbind(y_new, y)
}

dat2 <- data_frame(x1, x2, 
                   y1 = y_new[,1],
                   y2 = y_new[,2],
                   y3 = y_new[,3])

fig_dat2 <- dat2 %>%
  gather(x, x_val, 1:2) %>%
  gather(y, y_val, 1:3)

lm(y3 ~ x1 + x2, dat2) %>%
  summary

ggplot(fig_dat2, aes(x = x_val, y = y_val)) +
  geom_point() +
  facet_grid(y ~ x, scale = "free")

ggplot(dat2, aes(x = y1, y = y2)) +
  geom_point() 

list_dat2 <- list(obs = y_new,
                 x1 = dat2$x1,
                 x2 = dat2$x2,
                 n_sample = n)
```


```{r}
system.time(res2 <- stan(fit = fit,
           data = list_dat2,
           iter = n_iter,
           warmup = n_warm,
           thin = n_thin,
           chains = n_chains,
           control = list(adapt_delta = 0.95, max_treedepth = 10)))

fit_summary2 <- data.frame(summary(res2)$summary)

fit_summary2 %>% head(11) %>% print
fit_summary2 %>% tail %>% print

par2 <- extract(res2, par = c("a1", "a2",
                     "b1", "b2",
                     "c1", "c2", "c3"))

par_dat2 <- data_frame(par = c("a1", "a2",
                     "b1", "b2",
                     "c1", "c2", "c3") %>% rep(each = 1500),
           val = unlist(par2)) %>%
  mutate(dat = "MVN")

```

```{r}

par_dat3 <- bind_rows(par_dat, par_dat2) 

ggplot(par_dat3, aes(val, fill = dat)) +
  geom_histogram() +
  facet_wrap(~par, scale = "free", aes(alpha = 0.8))

```
