---
title: Boxplot
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE,
                      message=FALSE)
```


```{r, echo = F, message = F}
library(loo)
library(rstan)
library(dplyr)
library(scales)
library(memisc)
library(cowplot)

theme_set(theme_light())
```

# Boxplot

```{r}
setwd("..")

settings <- yaml::yaml.load_file("./settings.yml")
p_letters <- yaml::yaml.load_file("letters.yml")
source("fig_theme.r")

PA <- read_csv("./data/PA_res.csv")
GL <- read_csv("./data/GL_res.csv")

fills <- c("D" = settings$fills$D,
          "E" = settings$fills$E)

cols <- c("D" = settings$colors$D,
          "E" = settings$colors$E)

GL_dat <- GL %>%
  gather(LMA, Val, c(LMA, LMAs, LMAp)) %>%
  gather(Trait, Val2, c(Aarea, Rarea, LL,
                        Parea, Narea)) %>%
  mutate(DE = factor(DE,
          levels = c("D", "E", "U"))) %>%
  mutate(LMA = factor(LMA,
    labels = c("LMA", "LMAm", "LMAs"))) %>%
 # mutate(LMA = factor(LMA,
 #   labels = c("LMA~(~g~m^{-2})", "LMAm~(~g~m^{-2})", "LMAs~(~g~m^{-2})"))) %>%
  mutate(Trait = factor(Trait,
    levels = c("Aarea", "Rarea", "LL", "Narea", "Parea"))) %>%
  mutate(Trait2 = factor(Trait,
    labels = c("italic(A)[area]~(~mu~mol~m^{-2}~s^{-1})",
               "italic(R)[area]~(~mu~mol~m^{-2}~s^{-1})",
               "LL~(months)",
               "italic(N)[area]~(~g~m^{-2})",
               "italic(P)[area]~(~g~m^{-2})")))

PA_dat <- PA %>%
  gather(LMA, Val,
         c(LMA, LMAs, LMAp)) %>%
  gather(Trait, Val2, c(Aarea, Rarea, LL,
                        Parea, Narea, cell_area)) %>%
  mutate(LMA = factor(LMA,
    labels = c("LMA", "LMAm", "LMAs"))) %>%
 # mutate(LMA = factor(LMA,
 #   labels = c("LMA~(~g~m^{-2})", "LMAm~(~g~m^{-2})", "LMAs~(~g~m^{-2})"))) %>%
  mutate(site_strata = factor(site_strata,
          levels = c("WET_CAN", "DRY_CAN", "WET_UNDER", "DRY_UNDER"))) %>%
  mutate(Trait = factor(Trait,
    levels = c("Aarea", "Rarea", "LL", "Narea", "Parea", "cell_area"))) %>%
  mutate(Trait2 = factor(Trait,
    labels = c("italic(A)[area]~(~mu~mol~m^{-2}~s^{-1})",
               "italic(R)[area]~(~mu~mol~m^{-2}~s^{-1})",
               "LL~(months)",
               "italic(N)[area]~(~g~m^{-2})",
               "italic(P)[area]~(~g~m^{-2})",
               "italic(CL)[area]~(~g~m^{-2})"
               ))) %>%
  mutate(gr = factor(site_strata,
    labels = c("Sun-Wet",
               "Sun-Dry",
               "Shade-Wet",
               "Shade-Dry"
                      ))) %>%
  arrange(gr)

GL_dat_box <- GL_dat %>%
  filter(gr != "Unclassified") %>%
  dplyr::select(DE, Val, LMA) %>%
  mutate(gr = factor(DE,
                     levels = c("D", "E"))) %>%
  unique

theme_box <- function(base_size = 9,
                      base_family = "sans") {
  ret <- theme_LES() %+replace%
  theme(
    panel.border = element_blank(),
    panel.spacing = unit(0.5, "lines"),
    #plot.margin = margin(1,10,1,1),
    axis.line = element_line(colour = "black", size = 0.25),
    axis.title.y = element_text(margin = margin(t = 0,
                                                b = 0,
                                                l = -4,
                                                r = -4),
                                angle = 90)
        )
}

lab1 <- GL_dat_box %>%
  group_by(gr, LMA) %>%
  summarize(Val = max(Val)) %>%
  ungroup %>%
  arrange(LMA) %>%
  mutate(lab = p_letters$GL
         %>% unlist)

GL_box <- ggplot(GL_dat_box, aes(x = gr, y = Val, fill = gr)) +
  geom_boxplot(outlier.shape = 21, outlier.size = 1) +
  geom_text(data= lab1, aes(label = lab),
            vjust = -1,
            size = 8 * 5/14) +
  facet_grid(.~ LMA, labeller = label_parsed) +
  ylab(expression(atop("GLOPNET",
                LMA~(g~m^{-2})))) +
  xlab("") +
  scale_fill_manual(values = fills, guide = FALSE) +
  #guides(fill = FALSE, colour = FALSE) +
  #scale_x_log10(breaks = my_breaks(), expand = c(0.1, 0)) +
  scale_y_log10(breaks = my_breaks(), expand = c(0.1, 0)) +
  #scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
  #              labels = trans_format("log10", math_format(10^.x))) +
  theme_box()

fills2 <- c("Sun\nDry" = settings$fills$sun_dry,
          "Sun\nWet" = settings$fills$sun_wet,
          "Shade\nDry" = settings$fills$shade_dry,
          "Shade\nWet" = settings$fills$shade_wet,
          "Rand" = settings$fills$R)

cols2 <- c("Sun\nDry" = settings$colors$sun_dry,
          "Sun\nWet" = settings$colors$sun_wet,
          "Shade\nDry" = settings$colors$shade_dry,
          "Shade\nWet" = settings$colors$shade_wet,
          "Rand" = settings$colors$R)

PA_trim_dat <- PA_dat %>%
  count(sp) %>%
  filter(n >= 2) %>%
  inner_join(., PA_dat, by = "sp") %>%
  dplyr::select(gr, Val, LMA) %>%
  mutate(gr = factor(gr,
    levels = c("Sun-Dry", "Shade-Dry", "Sun-Wet", "Shade-Wet"))) %>%
  mutate(gr = factor(gr,
    labels = c("Sun\nDry", "Shade\nDry", "Sun\nWet", "Shade\nWet"))) %>%
  unique

lab2 <- PA_trim_dat %>%
  group_by(gr, LMA) %>%
  summarize(Val = max(Val)) %>%
  ungroup %>%
  arrange(LMA) %>%
  mutate(lab = p_letters$`PA-SI`
         %>% unlist)

PA_box <- ggplot(PA_trim_dat, aes(x = gr, y = Val, fill = gr, col = gr)) +
  geom_boxplot(outlier.shape = 21, outlier.size = 1) +
  geom_text(data= lab2, aes(label = lab),
            colour = "black",
            vjust = -1,
            size = 8 * 5/14) +
  facet_grid(.~ LMA, labeller = label_parsed) +
  #ylab(expression(Panama\nLMA~(g~m^{-2}~))) +
 # ylab(as.list(expression("Panama", paste("LMA (g ",m^{-2},")")))) +
  ylab(expression(atop("Panama",
                LMA~(g~m^{-2})))) +
  xlab("") +
 # labs(title = "moge") +
  scale_fill_manual(values = fills2, guide = FALSE) +
  scale_colour_manual(values = cols2, guide = FALSE) +
  #scale_x_log10(breaks = my_breaks(), expand = c(0.1, 0)) +
  scale_y_log10(breaks = my_breaks(), expand = c(0.1, 0)) +
  #scale_y_log10(#breaks = trans_breaks("log10", function(x) 10^x),
  #              labels = trans_format("log10", math_format(10^.x))) +
  theme_box() +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_text(colour = NA) # invinsible strip
        ) # +
 # annotation_logticks(size = 0.25,
 #   short = unit(0.1, "cm"),
 #   mid = unit(0.0, "cm"),
 #   long = unit(0.2, "cm")
 #                     )

box_main <- plot_grid(GL_box, PA_box,
          nrow = 2,
          #labels = c("(a)", "(b)"),
          label_size = 9)

print(box_main)

my_ggsave("./figs/box_main.png", box_main,
          width = 11.7,
          height = 11.7)

```
# Var

```{r}

cov_p <- function(data)cov(data$LMA, data$LMAp)
cov_s <- function(data)cov(data$LMA, data$LMAs)
var_t <- function(data)var(data$LMA)

var_p <- function(data)var(data$LMAp)
var_s <- function(data)var(data$LMAs)
cov_ps <- function(data)cov(data$LMAp, data$LMAs)
var_t <- function(data)var(data$LMA)


PA_cov <- PA %>%
  count(sp) %>%
#  filter(n >= 2) %>%
  inner_join(., PA, by = "sp") %>%
  mutate(gr = strata)

sun <- PA %>%
  filter(strata == "CAN")
shade <- PA %>%
  filter(strata != "CAN")

cov(sun$LMAs, sun$LMA)  /(cov(sun$LMAs, sun$LMA) + cov(sun$LMAp, sun$LMA))
cov(sun$LMAp, sun$LMA)  /(cov(sun$LMAs, sun$LMA) + cov(sun$LMAp, sun$LMA))
cov(shade$LMAs, shade$LMA)  /(cov(shade$LMAs, shade$LMA) + cov(shade$LMAp, shade$LMA))
cov(shade$LMAp, shade$LMA)  /(cov(shade$LMAs, shade$LMA) + cov(shade$LMAp, shade$LMA))
cov(GL$LMAs, GL$LMA)  /(cov(GL$LMAs, GL$LMA) + cov(GL$LMAp, GL$LMA))
cov(GL$LMAp, GL$LMA)  /(cov(GL$LMAs, GL$LMA) + cov(GL$LMAp, GL$LMA))


GL_cov <- GL %>%
  #filter(DE != "U") %>%
  mutate(gr = "GL")

var_dat <- bind_rows(PA_cov, GL_cov) %>%
  group_by(gr) %>%
  nest %>%
  mutate(var_LMAm = map_dbl(data, var_p)) %>%
  mutate(var_LMAs = map_dbl(data, var_s)) %>%
  mutate(cov_ms = 2 * map_dbl(data, cov_ps)) %>%
  mutate(var_total = map_dbl(data, var_t)) %>%
  dplyr::select(-data) %>%
  mutate(gr = ifelse(gr == "CAN", "PA Sun", gr))  %>%
  mutate(gr = ifelse(gr == "UNDER", "PA Shade", gr))  %>%
  mutate(gr = factor(gr,
    levels = c("GL", "PA Sun", "PA Shade")))

var_dat2 <- bind_rows(PA_cov, GL_cov) %>%
  group_by(gr) %>%
  nest %>%
  mutate(var_LMAm = map_dbl(data, cov_p)) %>%
  mutate(var_LMAs = map_dbl(data, cov_s)) %>%
  mutate(var_total = map_dbl(data, var_t)) %>%
  dplyr::select(-data) %>%
  mutate(gr = ifelse(gr == "CAN", "PA Sun", gr))  %>%
  mutate(gr = ifelse(gr == "UNDER", "PA Shade", gr))  %>%
  mutate(gr = factor(gr,
    levels = c("GL", "PA Sun", "PA Shade")))


var_dat_s <- var_dat2 %>%
  mutate(LMAm = var_LMAm / (var_LMAm + var_LMAs) * 100) %>%
  mutate(LMAs = var_LMAs / (var_LMAm + var_LMAs) * 100) %>%
  gather(var, val, c(LMAm, LMAs))

var_plt <- ggplot(var_dat_s, aes(x = gr, y = val, fill = var)) +
  geom_bar(position = "fill",stat = "identity") +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_grey(start=0.8, end=0.4) +
  xlab("") +
  ylab("% interspecific LMA variation") +
  theme(legend.position="top",
        legend.title = element_blank())

print(var_plt)

print(var_dat)

my_ggsave("../figs/var_plt.png", var_plt,
          width = 8,
          height = 8)

```


```{r}

sun <- PA %>%
  filter(strata == "CAN")

shade <- PA %>%
  filter(strata != "CAN")

lm(log(Aarea) ~ log(LMAp ) + log(LMAs), PA) %>%
  summary

lm(log(Aarea) ~ log(LMAp ) + log(LMAs), sun) %>%
  summary

lm(log(Aarea) ~ log(LMAp) + log(LMAs), shade) %>%
  summary

```
