---
title: Panama beta
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
---

LMAm + LMAs + light

```{r, echo = F, message = F}
library(loo)
library(rstan)
```

# Beta(1, 1)

```{r, cache=TRUE, comment=NA}
load("../data/PA_LMAms_L_more_obs.rda")
#load("./data/PA_LMAms_L2_more_obs.rda")
summary_PA <- data.frame(summary(res)$summary) %>% round(2)

DT::datatable(summary_PA)

get_stancode(res) %>% cat

PA <- dat %>%
  as_tibble %>%
  mutate(site2 = ifelse(site == "PNM", "DRY", "WET")) %>%
  mutate(sp_site_strata = paste(sp, site2, strata, sep = "_")) %>%
  mutate(site_strata = paste(site2, strata, sep = "_"))


para1 <- as.data.frame(res) %>% 
  as_tibble %>%
  dplyr::select(1:10, lp__) %>%
  mutate(Beta = "beta_1_1")

pmat <- as.data.frame(res) %>% 
  as_tibble %>%
  dplyr::select(starts_with("p[")) %>%
  as.matrix

tmp1 <- dat$LMA * (1 - t(pmat))
colnames(tmp1) <- str_c("mcmc", 1:ncol(tmp1))

tmp2 <- as_tibble(tmp1) %>%
  mutate(sp = str_c("sp", 1:n())) %>%
  mutate(LL = PA$LL) %>%
  mutate(site2 = PA$site2) %>%
  mutate(strata = PA$strata) %>%
  pivot_longer(1:4000, names_to = "mcmc", values_to = "LMAs")

tmp3 <- tmp2 %>%
  filter(mcmc == str_c("mcmc", 3001:3012))

ggplot(tmp3, aes(x = LMAs, y = LL, col = site2, shape = strata)) +
  #geom_point(alpha = 0., col = "grey") +
  facet_wrap( ~ mcmc , scale = "free") +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

```
 

# Beta(2, 2)

```{r, cache=TRUE, comment=NA}
load("../data/PA_LMAms_L2_more_obs.rda")

summary_PA <- data.frame(summary(res)$summary) %>% round(2)

DT::datatable(summary_PA)

para2 <- as.data.frame(res) %>% 
  as_tibble %>%
  dplyr::select(1:10, lp__) %>%
  mutate(Beta = "beta_2_2")

get_stancode(res) %>% cat


```

# Beta(0.5, 0.5)

Not convergent

```{r, cache=TRUE, comment=NA}
load("../data/PA_LMAms_L5_more_obs.rda")

summary_PA <- data.frame(summary(res)$summary) %>% round(2)

DT::datatable(summary_PA)

para3 <- as.data.frame(res) %>% 
  as_tibble %>%
  dplyr::select(1:10, lp__) %>%
  mutate(Beta = "beta_05_05")

get_stancode(res) %>% cat


```

# Beta(2, 2) without repulsive priors

```{r, cache=TRUE, comment=NA}
load("../data/PA_LMAms_L02_more_obs.rda")

summary_PA <- data.frame(summary(res)$summary) %>% round(2)

DT::datatable(summary_PA)

para4 <- as.data.frame(res) %>% 
  as_tibble %>%
  dplyr::select(1:10, lp__) %>%
  mutate(Beta = "beta_02_02")

get_stancode(res) %>% cat


```

# Beta(1, 1) without repulsive priors

```{r, cache=TRUE, comment=NA}
load("../data/PA_LMAms_L0_more_obs.rda")

summary_PA <- data.frame(summary(res)$summary) %>% round(2)

DT::datatable(summary_PA)

para5 <- as.data.frame(res) %>% 
  as_tibble %>%
  dplyr::select(1:10, lp__) %>%
  mutate(Beta = "beta_01_01")

get_stancode(res) %>% cat


```

# Beta(1, 1) without repulsive priors

```{r, cache=TRUE, comment=NA}
load("../data/PA_LMAms0_more_obs.rda")

summary_PA <- data.frame(summary(res)$summary) %>% round(2)

DT::datatable(summary_PA)

para6 <- as.data.frame(res) %>% 
  as_tibble %>%
  dplyr::select(1:10, lp__) %>%
  mutate(Beta = "beta_01_01_no_light")

get_stancode(res) %>% cat


```

# Kiku

```{r, cache=TRUE, comment=NA}
load("../data/PA_latent_kiku_more_obs.rda")

summary_PA <- data.frame(summary(res)$summary) %>% round(2)

DT::datatable(summary_PA)

para7 <- as.data.frame(res) %>% 
  as_tibble %>%
  dplyr::select(1:7, lp__) %>%
  mutate(Beta = "kiku")

get_stancode(res) %>% cat

```


# Fig

```{r}

fig_dat <- bind_rows(para1, para2, para4, para5, para6) %>% 
  pivot_longer(-Beta, names_to = "para", values_to = "val") %>%
  filter(para != "tau")

ggplot(fig_dat, aes(y = val, x = Beta, fill = Beta)) +
  geom_violin(draw_quantiles = c(0.025, 0.25,  0.5, 0.75, 0.975)) +
  facet_wrap( ~ para, scale = "free")


```
