---
title: Var sim
---

```{r, echo = F}
settings <- yaml::yaml.load_file("settings.yml")
r_vals <- yaml::yaml.load_file("r_val.yml")
p_letters <- yaml::yaml.load_file("letters.yml")
library(cowplot)
source("fig_theme.r")
```

```{r, echo = F}
var_vec <- seq(0.1, 1, length = 400)
p_scale <- var_vec
a_sd <- var_vec
#p_scale <- c(0.1, 0.5, 1)
#a_sd <- c(0.1, 0.5, 1)

para <- expand.grid(var_vec, 0.5, p_scale, 0.01)
colnames(para) <- c("LMAp_sd", "LMAs_sd", "Aarea_scale", "mu_sd")

dat_fun <- function(n){
  LMAp <- rlnorm(100, log(40), para[n,1])
  LMAs <- rlnorm(100, log(80), para[n,2])
  log_mu <- 1.5 + para[n,3] * log(LMAp)
  Aarea <- rlnorm(100, log_mu, para[n,4])
  dat <- data_frame(LMAp, LMAs, Aarea) %>%
    mutate(LMA = LMAp + LMAs) %>%
    filter(is.finite(Aarea))
  dat
}

cor_fun <- function(data) {
  cor(log(data$Aarea), log(data$LMA))
}

b_fun <- function(data) {
  res <- lm(log(Aarea) ~ log(LMA), data = data)
  res[[1]][2]
}

var1_fun <- function(data){
  var(log(data$LMAp))
}

var2_fun <- function(data){
  var(log(data$LMAs))
}
var12_fun <- function(data){
  var((data$LMAp))
}

var22_fun <- function(data){
  var((data$LMAs))
}


before <- proc.time()
para2 <- para %>%
  mutate(res = map(1:nrow(.), dat_fun)) %>%
  as_data_frame
after <- proc.time()
after - before

para3 <- para2 %>%
  mutate(r = map_dbl(res, cor_fun)) %>%
  mutate(b = map_dbl(res,b_fun)) %>%
  mutate(v1 = map_dbl(res,var1_fun)) %>%
  mutate(v2 = map_dbl(res,var2_fun)) %>%
  mutate(v12 = map_dbl(res,var12_fun)) %>%
  mutate(v22 = map_dbl(res,var22_fun)) %>%
  dplyr::select(-res) %>%
  mutate(va_ps = LMAp_sd / LMAs_sd) %>%
  mutate(va_ps2 = v1/v2) %>%
  mutate(va_ps3 = v12/v22)
  #mutate(va_ps = as.integer(va_ps))

DT::datatable(para3)

#simvar <- ggplot(para3, aes(x = va_ps, y = Aarea_scale, fill = r)) +
#  geom_raster() +
#  scale_fill_gradient2(midpoint = median(para3$r))

aa <- c(0.1, 0.5, 1, 2, 10)
#simvar <- ggplot(para3 %>% 
#                 filter(b < 1.1) %>%
#                 filter(b > -0.1), aes(x = va_ps, y = Aarea_scale, fill = b)) +
simvar <- ggplot(para3, aes(x = va_ps, y = Aarea_scale, fill = b)) +
  geom_raster() +
  scale_fill_gradient2(midpoint = 0.5,
                       name = "Mass \nproportionality") +
theme(panel.background = element_rect(fill = "#073642")) +
xlab("sigma_m/sigma_s") +
ylab("Scaling slope")

simvar2 <- ggplot(para3, aes(x = va_ps3 %>% round(1), y = Aarea_scale, fill = b)) +
  geom_raster() +
  scale_fill_gradient2(midpoint = 0.5,
                       name = "Mass \nproportionality") +
theme(panel.background = element_rect(fill = "#073642")) +
xlab("Var(LMAm)/Var(LMAs)") +
ylab("Scaling slope") +
scale_x_log10(limits=c(0.1, 10)) 

simvar2

plot_grid(simvar, simvar2)

simvar3 <- ggplot(para3, aes(x = va_ps3 %>% round(1), y = Aarea_scale, fill = b)) +
  geom_raster() +
  scale_fill_gradient2(midpoint = 0.5,
                       name = "Mass \nproportionality") +
theme(panel.background = element_rect(fill = "#073642")) +
xlab("Var(LMAm)/Var(LMAs)") +
ylab("Scaling slope") +
xlim(0, 8)

simvar3

my_ggsave("./figs/simvar3.png",
          simvar3,
          height = 6,
          width = 10)

```

