# Model estimation

The logarithms of *A*~area~, LL, and *R*~area~ in Table 1 in the main text are assumed to have a multivariate normal distribution (MVN):

\begin{align}
\left(
\begin{array}{ccc}
\mathrm{ln}[A_{\mathrm{area} \, i}]&\\
\mathrm{ln}[\mathrm{LL}_i]&\\
\mathrm{ln}[R_{\mathrm{area} \, i}]&
\end{array}
\right)
\sim \mathrm{MVN}
\left(
\begin{array}{ccc}
\mu_{1i}&\\
\mu_{2i}&, \boldsymbol{\Sigma}\\
\mu_{3i}&
\end{array}
\right), (\#eq:MVN)
\end{align}

\begin{align}
\boldsymbol{\Sigma} =
\left(
\begin{array}{ccc}
\sigma_1^2 &\rho_{12}\sigma_1\sigma_2 &\rho_{13}\sigma_1\sigma_3 \\
\rho_{12}\sigma_1\sigma_2&\sigma_2^2 &\rho_{23}\sigma_2\sigma_3 \\
\rho_{13}\sigma_1\sigma_3&\rho_{23}\sigma_2\sigma_3 &\sigma_3^2
\end{array}
\right) (\#eq:Sigma)
\end{align}

where $\mu_{1-3,i}$ is the expecation on the log scale; i.g., $\mu_{1i} = \mathrm{ln}\alpha_0 + \alpha_1 \mathrm{ln\; LMA}_i + \sigma_1^2/2$ for the LMA model in Table 1 in the main text; $\boldsymbol{\Sigma}$ is the covariance matrix; $\sigma_1$, $\sigma_2$, and $\sigma_3$ are standard deviations of $\mu_{1-3}$.

The covariance matrix in Eq.@ref(eq:MVN) was decomposed as

$\boldsymbol {\mathrm \Sigma} = \mathrm {diag}(\boldsymbol \sigma){\boldsymbol \Omega}\mathrm {diag}(\boldsymbol \sigma) = \mathrm {diag}({\boldsymbol \sigma}){\boldsymbol LL}\prime \mathrm {diag}({\boldsymbol \sigma})$ using a Cholesky decomposition, where $\boldsymbol \sigma$ is a vector of $\sigma_{1}$, $\sigma_{2}$, and $\sigma_{3}$; $\boldsymbol \Omega$ is a correlation matrix of $\rho_{12}$, $\rho_{13}$, and $\rho_{23}$; and $\boldsymbol L$ is a lower triangular matrix. 
Instead of assigning prior distributions on directly, priors were assigned on and *L* to avoid a strong dependence between and [@Lewandowski2009; @Alvarez2014].


We used independent non-informative prior distributions for all parameters, including latent variables *f~ik~* for each leaf sample. 
A prior for $\boldsymbol L$ was specified as a so-called LKJ distribution with shape parameter 1 [@Lewandowski2009], which is identical to a uniform distribution on the space of correlation matrices. 
Priors for $\boldsymbol \sigma$ were specified as half-Cauchy distributions with location 0 and scale 5. 
Priors for $log\, \alpha_0$, $log\, \beta_0$, $log\, \gamma_0$, $\alpha_i$, $\beta_i$ and $\gamma_i$ were specified as normal distributions with mean 0 and variance 10. 
Priors for *f~i~* in Eqs. 4-6 and 8 were specified as uniform distributions with range (0, 1).

Posterior distributions of all parameters were estimated using the Hamiltonian Monte Carlo algorithm (HMC) implemented in Stan [@Carpenter2017]. 
The Stan code use to fit models are also available from Github at: [https://github.com/mattocci27/LMAmLMAs](https://github.com/mattocci27/LMAmLMAs). 
Some parameters are exchangeable in our model. For example, $(f_i, \ \alpha_m, \ \alpha_s)$ = (0.2, 0.5, 1.0) and (0.8, 1.0, 0.5) yield the identical likelihood, which results in bimodal distributions of the posterior distributions of parameters (See X). 
To avoid this non-identifiability, i) we simply switched labels so that $\alpha_m$ > $\alpha_s$ (LMAm is associated with metabolic rates by our definition) or ii) we constrained  $\alpha_m$ > $\alpha_s$. 
Both methods yield qualitatively similar results and we report the second method for the main text. 
Convergence of the posterior distribution was assessed with the Gelman-Rubin statistic with a convergence threshold of 1.1 for all diagnostics [@Gelman2014].
