---
title: Var para
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE,
                      message=FALSE)
```


```{r, echo = T, message = F}
rm(list = ls())
library(rstan)
library(tidyverse)
```

# GL

```{r}
load("../rda/GL_LMAms_more_obs.rda")
GL <- dat
GLres <- res
pmat <- extract(res, "p")[[1]]
n <- 4000

LMAp_var <- numeric(n)
LMAs_var <- numeric(n)

for (i in 1:n) {
  LMAp <- pmat[i,] * GL$LMA
  LMAs <- (1 - pmat[i,]) * GL$LMA
  LMAp_var[i] <- cov(LMAp, GL$LMA)
  LMAs_var[i] <- cov(LMAs, GL$LMA)
}

hist(LMAs_var / var(GL$LMA) * 100)
hist(LMAp_var / var(GL$LMA) * 100)

summary(LMAs_var / var(GL$LMA) * 100)
summary(LMAp_var / var(GL$LMA) * 100)

```

# sun

```{r}
load("../rda/PA_LMAms_L0_more_obs.rda")
PA <- dat %>%
  mutate(tmp = 1:n())
PAres <- res
pmat <- extract(res, "p")[[1]]
n <- 4000

sun <- PA %>% filter(strata == "CAN")
shade <- PA %>% filter(site2 != "CAN")

LMAp_sun_var <- numeric(n)
LMAs_sun_var <- numeric(n)

for (i in 1:n) {
  LMAp_sun <- pmat[i, sun$tmp] * sun$LMA
  LMAs_sun <- (1 - pmat[i, sun$tmp]) * sun$LMA
  LMAp_sun_var[i] <- cov(LMAp_sun, sun$LMA)
  LMAs_sun_var[i] <- cov(LMAs_sun, sun$LMA)
}

hist(LMAs_sun_var / var(sun$LMA) * 100)
hist(LMAp_sun_var / var(sun$LMA) * 100)

summary(LMAs_sun_var / var(sun$LMA) * 100)
summary(LMAp_sun_var / var(sun$LMA) * 100)

LMAp_sun <- apply(1 - pmat[, sun$tmp], 2, median) * sun$LMA 
cov(LMAp_sun, sun$LMA) / var(sun$LMA)

```

# shade

```{r}
LMAp_shade_var <- numeric(n)
LMAs_shade_var <- numeric(n)

for (i in 1:n) {
  LMAp_shade <- pmat[i, shade$tmp] * shade$LMA
  LMAs_shade <- (1 - pmat[i, shade$tmp]) * shade$LMA
  LMAp_shade_var[i] <- cov(LMAp_shade, shade$LMA)
  LMAs_shade_var[i] <- cov(LMAs_shade, shade$LMA)
}

hist(LMAs_shade_var / var(shade$LMA) * 100)
hist(LMAp_shade_var / var(shade$LMA) * 100)

summary(LMAs_shade_var / var(shade$LMA) * 100)
summary(LMAp_shade_var / var(shade$LMA) * 100)
```

## yml

```{r}
# R values

output <- "../var_val.yml"
out <- file(paste(output), "w") # write
writeLines(paste0("GL: ",
  median(LMAs_var / var(GL$LMA) * 100) %>% round(0)),
           out,
           sep = "\n")
writeLines(paste0("sun: ",
  median(LMAs_sun_var / var(sun$LMA) * 100) %>% round(0)),
           out,
           sep = "\n")
writeLines(paste0("shade: ",
  median(LMAs_shade_var / var(shade$LMA) * 100) %>% round(0)),
           out,
           sep = "\n")
close(out)

```
