FROM mattocci/rstan:3.6.3

RUN install2.r -n -1 --skipinstalled --error \
  --deps TRUE \
    pbmcapply \
    scales \
    cowplot \
    ggrepel \
    png \
    grid \
    lazyeval \
    latex2exp \
    kableExtra \
    multcompView
