---
output:
  bookdown::pdf_book:
    fig_caption: true
    keep_tex: yes
    toc: no
    number_sections: no
    includes:
        in_header: format.sty
    pandoc_args:
      - "--filter"
      - "pandoc-crossref"
  bookdown::word_document2:
    fig_width: 6
    fig_caption: true
    reference_docx: rmd_style.docx
    #pandoc_args:
    #- "--filter"
    #- "pandoc-crossref"
    #- "--mathml"
fontsize: 12pt
geometry: margin=1in
link-citations: yes
csl: je.csl
bibliography: ref.bib
---

```{r, echo = FALSE}
library(tidyverse)
library(methods)
library(knitr)
library(png)
```


```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)

getOutputFormat <- function() {
  output <- rmarkdown:::parse_yaml_front_matter(
    readLines(knitr::current_input())
    )$output
  if (is.list(output)){
    return(names(output)[1])
  } else {
    return(output[1])
  }
}

if(getOutputFormat() == 'pdf_document') {
  library(Cairo)
  knitr::opts_chunk$set(dev="cairo_pdf")
}
```
