---
title: "LMAp-LMAs intro"
output:
  bookdown::word_document2:
       fig_width: 6
       #reference_docx: rmd_style.docx
       pandoc_args:
         - "--filter"
         - "pandoc-crossref"
         - "--mathml"
---

Each section corresponds to each potential paragraph.

## Problem of one-dimensional LES

The LES captures tight relationships among leaf mass per area (LMA), leaf lifespan (LL), and mass-normalized leaf traits related to carbon fixation and nutrient use ranging from short-lived leaves with high photosynthetic potential and fast returns on investment to long-lived leaves with low photosynthetic potential and slow returns (Wright et al., 2004; Westoby & Wright, 2006; Reich, 2014). The strong correlations suggest the presence of a single dominant axis of leaf functional variation (Wright et al. 2004). However, recent analyses suggest that the strong correlations are largely the result of high interspecific variation in LMA combined with mass-normalization of area-dependent traits (Osnas et al. 2013; Lloyd et al. 2013). Thus, although mass-normalization and the LES can be justified based on economic principles (Westoby et al. 2013), the evidence for a single dominant axis is questionable.

## Multiple dimensions in trait variation

Furthermore, different leaf assemblages exhibit different patterns of trait variation with respect to leaf mass and leaf area. For example, across global species, whole-leaf values of traits related to photosynthesis and metabolism (e.g., the photosynthetic capacity of an entire leaf, units = moles CO~2~ fixed per-unit time; or the total amount of N or P in an entire leaf, units = grams  of nitrogen or phosphorus) tend to be roughly proportional to leaf area; whereas across intraspecific light gradients these same whole-leaf trait values tend to be roughly proportional to leaf mass. Functional groups (e.g., deciduous vs. evergreen angiosperms) also differ from each other in terms of how interspecific trait variation (within a given functional group) depends on leaf mass vs. area.These divergent patterns in leaf trait variation suggest the presence of multiple drivers of trait variation, which may be difficult to capture with a single axis.

## One promising (possible) approach for understanding cause and consequence of leaf trait variation is to understand mass vs area (or photosynthetic vs structural components)

One promising approach for understanding cause and consequence of leaf trait variation is to conceptualize LMA as the sum of  photosynthetic and structural components (Osnas et al. in press). Although this two-dimensional model of trait variation is simplistic (e.g., there is no explicit treatment of leaf hydraulics), it provides qualitative insights into the causes of the above divergent trait patterns, because variation in LMAp leads to mass-dependence of photosynthetic and metabolic traits, whereas variation in LMAs leads to area-dependence of these same traits (supplement ?).


For example, …[perhaps explain how LMAp-LMAs can explain area-dependence of global flora and mass-dependence within species


However, the above conceptual model has not been translated into a quantitative model that predicts trait values, which limits our capacity to test and apply the model. One approach to developing a quantitative framework would be to directly measure LMAp and LMAs, and then to estimate relationships between these traits and other traits of interest (e.g., Amax, Rdark, and LL). However, although certain leaf mass components can be neatly partitioned to either LMAp or LMAs (e.g., chloroplasts contribute to photosynthesis, but not structure), other leaf mass components cannot. For example, thick cell walls contribute to structural toughness, but at least some cell wall mass is required for the biomechanical support that enables photosynthesis. An alternative approach to implementing a quantitative form of the LMAp-LMAs model, and the one we explore in this paper, is to specify hypotheses for how LMAp and LMAs relate to measured traits (e.g., Amax, Rdark, and LL) in the form of a quantitative model, and to evaluate the model using statistical methods.

## Objectives

- We show more a realistic (or concrete) version of the above conceptual model than the previous study (Osnas et al. in press) using leaf trait data from two tropical forest sites and GLOPNE.
- The goal of our analysis is to evaluate if the inferred LMAp and LMAs values can explain divergent patterns in leaf trait data, and if so, to use the model to elucidate the causes of these divergent patterns.
- First, we describe the framework.
- Questions:
    1. What is the relative importance of LMAp vs. LMAs in explaining variation in LMA within and among species?
    1. Do LMAp and LMAs differ between evergreen and deciduous species, and between sun and shade leaves?
    1. How are measurable leaf photosynthetic and structural traits (e.g., concentrations of nitrogen and cellulose) related to LMAp and LMAs?
