---
output:
  bookdown::pdf_book:
    fig_caption: true
    keep_tex: yes
    toc: no
    number_sections: no
    includes:
        in_header: format.sty
    pandoc_args:
      - "--filter"
      - "pandoc-crossref"
  bookdown::word_document2:
       fig_width: 6
       reference_docx: rmd_style.docx
       pandoc_args:
         - "--filter"
         - "pandoc-crossref"
fontsize: 12pt
sansfont: Times New Roman
geometry: margin=1in
link-citations: yes
csl: je.csl
bibliography: ref.bib
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r caching, include=FALSE}
library(methods)
library(knitr)
library(kableExtra)
library(png)
library(grid)
library(pander)
source("rmd_func.r")

```


#`r page_break("Tables")`

# Tables

```{r model-tab, anchor = "table", tab.cap="Summary of results for the Potential LL model and the Optimal LL model.n.obs; number of samples analyzed. WAIC is Watanabe-Akaike information criterion, which is a predictive information criterion for Baysian models, with lower values indicating a more parsimonious model. elpd_loo is expected log predictive density from leave-one-out cross-validation. Larger values of elpd_loo indicate a more parsimonious model."}

d <- read_csv("../data/model_comp.csv")

if ("docx" == knitr::opts_knit$get("rmarkdown.pandoc.to")) {
  knitr::kable(d) #%>%
} else if ("html" == knitr::opts_knit$get("rmarkdown.pandoc.to")) {
  knitr::kable(d, format = "html", escape = FALSE)
} else {
  knitr::kable(d, format = "latex")
}

```

`r page_break("Figures")`

```{r GL-rand, echo = F, dpi = 300, fig.width = 6, fig.height = 6, fig.cap = "Leaf-trait relationships in the randomized GLOPNET dataset with no functional correlations involving LMA, *A*~area~, *R*~area~ and LL. Symbols show 1 of 10 randomized datasets, in which LMA was randomized among all leaves in the GLOPNET dataset we analyzed."}

img <- readPNG("../figs/GL_rand.png", native = TRUE, info = TRUE)
grid.raster(img, interpolate=F)

```

`r page_break("")`

```{r PA-rand, echo = F, dpi = 300, fig.width = 6, fig.height = 6, fig.cap = "Observed vs. predicted leaf lifespan (LL) in the Optimal LL Model (Eq. 8). Predicted LL values are posterior means. The dashed line indicates the 1:1 relationship. Symbols show 1 of 10 randomized datasets, in which LMA was randomized among all leaves in the Panama dataset we analyzed."}

img <- readPNG("../figs/PA_rand.png", native = TRUE, info = TRUE)
grid.raster(img, interpolate=F)

```

`r page_break("")`

```{r LL-rand, echo = F, dpi = 300, fig.width = 6, fig.height = 6, fig.cap = "Leaf-trait relationships in the randomized Panama dataset. Symbols show 1 of 10 randomized datasets, in which LMA was randomized among all leaves in the Panama dataset we analyzed."}

img <- readPNG("../figs/LL_rand.png", native = TRUE, info = TRUE)
grid.raster(img, interpolate=F)

```

`r page_break("")`

```{r LMAmsplt, echo = F, dpi = 300, fig.width = 6, fig.height = 6, fig.cap = "Pearson correlation coefficients for posterior medians of LMAm vs LMAs in the (a) GLOPNET and (b) Panama datasets. The non-significant *r* values indicate that a single axis could not accurately represent the two-dimensional space. Symbols as in Main Text Figs. 1-2."}

img <- readPNG("../figs/LMAms.png", native = TRUE, info = TRUE)
grid.raster(img, interpolate=F)

```

`r page_break("")`

```{r box-SI, echo = F, dpi = 300, fig.width = 6, fig.height = 6, fig.cap = "Boxplots comparing leaf mass per area (LMA), photosynthetic leaf mass per area (LMAp; posterior means), and structural leaf mass per area (LMAs; posterior means) across sites (wet and dry) and canopy strata (sun and shade) in Panama. The results shown here include all leaves in the Panama dataset, whereas Fig. 5 in the main text only includes Panama species for which both sun and shade leaves were available. Boxplot symbols as in Fig. 5. Groups sharing the same letters are not significantly different (P > 0.05; t-tests)."}

img <- readPNG("../figs/box_SI.png", native = TRUE, info = TRUE)
grid.raster(img, interpolate=F)

```

`r page_break("")`

```{r GL-NP, echo = F, dpi = 300, fig.width = 6, fig.height = 6, fig.cap = "Measured traits related to photosynthesis and metabolism (nitrogen and phosphorus per-unit leaf area; Narea and Parea) are positively correlated with LMA and with estimates (posterior means) of the photosynthetic and structural LMA components (LMAp and LMAs, respectively) in the GLOPNET dataset. LMAp yields stronger correlations and more consistent relationships compared to LMA and LMAs; e.g., evergreen and deciduous leaves align along a single relationship in panel b, but not in panels a or c."}

img <- readPNG("../figs/GL_NP.png", native = TRUE, info = TRUE)
grid.raster(img, interpolate=F)

```
